name: sweet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cython==3.2.2
      - datasets==4.4.1
      - dill==0.4.0
      - docopt==0.6.2
      - evaluate==0.4.6
      - exceptiongroup==1.3.1
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.4
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==2.1.5
      - mosestokenizer==1.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.2.1
      - nltk==3.9.2
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openfile==0.0.7
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyarrow==21.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - toolwrapper==2.1.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uctools==1.3.0
      - urllib3==1.26.13
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /nfs/home/ryanyao/miniconda3/envs/sweet
